In [1]:
import pandas as pd
import numpy as np

In [224]:
df = pd.read_csv(r"C:\Users\Aishwarya\Documents\GitHub\OceanCleanup\Cleaned\clean6.csv")

In [116]:
df.head(2)

,Unnamed: 0,Zone,State,Country,GPS,Cleanup Type,Cleanup Date,Group Name,Adults,Children,...,Other Trash (Clean Swell),Condoms,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected
0,1,"Cuyahoga County, OH, USA","Ohio, USA",United States,"41.49742, -81.56505","Land (beach, shoreline and inland)",12/22/14,NaN,1,0,...,0,0,0,0,0,0,0,0,0,3
1,2,"Fairfax County, VA, USA","Virginia, USA",United States,"38.87456, -77.24428","Land (beach, shoreline and inland)",12/24/14,NaN,1,0,...,0,0,0,0,0,0,0,0,2,10

In [117]:
df[['Lat','Long']] = df.GPS.str.split(",",expand=True,)

In [126]:
df.head(2)

,Unnamed: 0,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
0,1,"Cuyahoga County, OH, USA","Ohio, USA",United States,"Land (beach, shoreline and inland)",12/22/14,NaN,1,0,1,...,0,0,0,0,0,0,0,3,41.49742,-81.56505
1,2,"Fairfax County, VA, USA","Virginia, USA",United States,"Land (beach, shoreline and inland)",12/24/14,NaN,1,0,1,...,0,0,0,0,0,0,2,10,38.87456,-77.24428

In [132]:
#df = df.drop(["GPS"],axis = 1)
first_column = df.columns[0]
df = df.drop([first_column], axis=1)

df.head(2)

,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
0,"Cuyahoga County, OH, USA","Ohio, USA",United States,"Land (beach, shoreline and inland)",12/22/14,NaN,1,0,1,0,...,0,0,0,0,0,0,0,3,41.49742,-81.56505
1,"Fairfax County, VA, USA","Virginia, USA",United States,"Land (beach, shoreline and inland)",12/24/14,NaN,1,0,1,0,...,0,0,0,0,0,0,2,10,38.87456,-77.24428

In [133]:
df1 = df.loc[df["Zone"].isna()]

len(df1)

235

In [134]:
df1.head(2)

,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
1335,NaN,NaN,United States,"Land (beach, shoreline and inland)",8/24/16,NaN,1,0,1,0,...,0,0,0,0,0,0,0,1,33.12618,-117.44777
1348,NaN,NaN,United States,"Land (beach, shoreline and inland)",8/26/16,NaN,1,0,1,0,...,0,0,0,0,0,0,0,1,33.15991,-117.48768

In [154]:
df[:22329]

,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
0,"Cuyahoga County, OH, USA","Ohio, USA",United States,"Land (beach, shoreline and inland)",12/22/14,NaN,1,0,1,0,...,0,0,0,0,0,0,0,3,41.49742,-81.56505
1,"Fairfax County, VA, USA","Virginia, USA",United States,"Land (beach, shoreline and inland)",12/24/14,NaN,1,0,1,0,...,0,0,0,0,0,0,2,10,38.87456,-77.24428
2,"Washington, DC, USA","District of Columbia, USA",United States,"Land (beach, shoreline and inland)",2/19/15,NaN,1,0,1,0,...,0,0,0,0,0,0,0,4,38.90733,-77.04405
3,"Washington, DC, USA","District of Columbia, USA",United States,"Land (beach, shoreline and inland)",2/19/15,NaN,1,0,1,0,...,0,0,0,0,0,0,0,14,38.90733,-77.0441
4,"Washington, DC, USA","District of Columbia, USA",United States,"Land (beach, shoreline and inland)",3/10/15,NaN,1,0,1,2,...,0,0,0,1,0,0,1,17,38.90728,-77.04411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22324,"Lincoln County, OR, USA","Oregon, USA",United States,"Land (beach, shoreline and inland)",9/29/18,OC - SOLVE,3,0,3,12,...,0,0,0,0,0,0,188,291,44.6596,-124.05536
22325,"Tillamook County, OR, USA","Oregon, USA",United States,"Land (beach, shoreline and inland)",9/29/18,Troop7150,3,0,3,1,...,0,0,0,2,0,0,10,19,45.3296,-123.96843
22326,NaN,NaN,United States,"Land (beach, shoreline and inland)",9/29/18,Troop 7150,1,0,1,6,...,0,0,0,3,0,0,50,88,45.33714,-123.97507
22327,"Clatsop County, OR, USA","Oregon, USA",United States,"Land (beach, shoreline and inland)",9/29/18,Solve,4,0,4,31,...,0,0,0,3,0,0,413,749,45.99228,-123.93097
22328,NaN,NaN,United States,"Land (beach, shoreline and inland)",9/29/18,NaN,2,0,2,37,...,0,0,0,8,0,0,502,674,20.9009,-156.45832

In [184]:
import urllib, json, requests

with urllib.request.urlopen("https://geo.fcc.gov/api/census/area?lat=20.9009&lon=-156.45832&format=json") as url:
    data = json.loads(url.read().decode())
    print(data)
    
print(json.dumps(data, indent=4, sort_keys=True))

print(data['results'])
print(data['results'][0]['county_name'])
print(type(data['results'][0]['state_code']))
#print(data['results'][0]['county_name'])
print(type(data['results'][0]['county_name']))
print(type(data['results'][0]['state_code']))

{'input': {'lat': 20.9009, 'lon': -156.45832}, 'results': [{'block_fips': '150090319001024', 'bbox': [-156.46542, 20.89674, -156.44693, 20.909202], 'county_fips': '15009', 'county_name': 'Maui', 'state_fips': '15', 'state_code': 'HI', 'state_name': 'Hawaii', 'block_pop_2015': 0, 'amt': 'AMT008', 'bea': 'BEA172', 'bta': 'BTA222', 'cma': 'CMA386', 'eag': 'EAG006', 'ivm': 'IVM386', 'mea': 'MEA048', 'mta': 'MTA047', 'pea': 'PEA042', 'rea': 'REA008', 'rpc': 'RPC005', 'vpc': 'VPC008'}]}
{
    "input": {
        "lat": 20.9009,
        "lon": -156.45832
    },
    "results": [
        {
            "amt": "AMT008",
            "bbox": [
                -156.46542,
                20.89674,
                -156.44693,
                20.909202
            ],
            "bea": "BEA172",
            "block_fips": "150090319001024",
            "block_pop_2015": 0,
            "bta": "BTA222",
            "cma": "CMA386",
            "county_fips": "15009",
            "county_name": "Maui",
            "eag": "EAG006",
            "ivm": "IVM386",
            "mea": "MEA048",
            "mta": "MTA047",
            "pea": "PEA042",
            "rea": "REA008",
            "rpc": "RPC005",
            "state_code": "HI",
            "state_fips": "15",
            "state_name": "Hawaii",
            "vpc": "VPC008"
        }
    ]
}
[{'block_fips': '150090319001024', 'bbox': [-156.46542, 20.89674, -156.44693, 20.909202], 'county_fips': '15009', 'county_name': 'Maui', 'state_fips': '15', 'state_code': 'HI', 'state_name': 'Hawaii', 'block_pop_2015': 0, 'amt': 'AMT008', 'bea': 'BEA172', 'bta': 'BTA222', 'cma': 'CMA386', 'eag': 'EAG006', 'ivm': 'IVM386', 'mea': 'MEA048', 'mta': 'MTA047', 'pea': 'PEA042', 'rea': 'REA008', 'rpc': 'RPC005', 'vpc': 'VPC008'}]
Maui
<class 'str'>
<class 'str'>
<class 'str'>

In [136]:
import requests

str2 = "https://geo.fcc.gov/api/census/area?lat="+ str(df1["Lat"][1335]).replace(" ","") + "&lon=" + str(df1["Long"][1335]).replace(" ","") + "&format=json"
print(str2)

https://geo.fcc.gov/api/census/area?lat=33.12618&lon=-117.44777&format=json

In [94]:
#first_column = df1.columns[0]
#second_column = df1.columns[1]
#df1 = df1.drop([first_column], axis=1)
#df1 = df1.drop([second_column],axis = 1)

In [174]:
index_list = df1.index.tolist()
print(index_list)

[1335, 1348, 1444, 4169, 7017, 7018, 7019, 7020, 7021, 7022, 7023, 7024, 7025, 7026, 7027, 7028, 7029, 7030, 7031, 7032, 7033, 7039, 7040, 8757, 11205, 13740, 13741, 13742, 13743, 13744, 13745, 13746, 13747, 13748, 13749, 13751, 13752, 13753, 17528, 19049, 21346, 21674, 21732, 21816, 21826, 21938, 21964, 22080, 22088, 22091, 22095, 22099, 22102, 22132, 22139, 22154, 22169, 22184, 22252, 22258, 22291, 22313, 22326, 22328, 22337, 22347, 22348, 22349, 22350, 22351, 22390, 22424, 22425, 22426, 22427, 22428, 22429, 22433, 22434, 22435, 22438, 22439, 22446, 22447, 22448, 22449, 22450, 22451, 22452, 22453, 22454, 22455, 22456, 22457, 22458, 22459, 22460, 22484, 22529, 22530, 22531, 22534, 22535, 22540, 22547, 22569, 22572, 22584, 22618, 22621, 22640, 22641, 22761, 22762, 22764, 22817, 22825, 22857, 22858, 22860, 22861, 22862, 22863, 22886, 22904, 23123, 23145, 23162, 23189, 23190, 23191, 23231, 23246, 23249, 23283, 23328, 23336, 23409, 23460, 23515, 23601, 23605, 23660, 23729, 23740, 23746, 23806, 23951, 23953, 23976, 23977, 23981, 23984, 24025, 24033, 24063, 24113, 24115, 24116, 24117, 24118, 24119, 24176, 24179, 24183, 24184, 24236, 24237, 24239, 24243, 24244, 24245, 24247, 24248, 24250, 24251, 24252, 24253, 24254, 24264, 24277, 24405, 24526, 24528, 24542, 24605, 24678, 24680, 24689, 24700, 24727, 25341, 25493, 25506, 25575, 25603, 25605, 25802, 25946, 26148, 26165, 26895, 26901, 26925, 26995, 26996, 27012, 27013, 27016, 27030, 27107, 27321, 27344, 27349, 27402, 27433, 27475, 27602, 27610, 27613, 27617, 27721, 27794, 27884, 27908, 27919, 27941, 27944, 27959, 27974, 27985, 27997, 28032, 28036, 34410]

In [187]:
key_list = index_list
value_list_zone = []
value_list_state = []
for i in index_list:
    str2 = "https://geo.fcc.gov/api/census/area?lat="+str(df1["Lat"][i]).replace(" ","")+"&lon="+str(df1["Long"][i]).replace(" ","")+"&format=json"
    with urllib.request.urlopen(str2) as url:
        data = json.loads(url.read().decode())
        if len(data['results']) != 0:
            value_list_zone.append(data['results'][0]['county_name'] + " County, " + data['results'][0]['state_code'] + ", USA")
            value_list_state.append(data['results'][0]['state_name'] + ", USA")
        else:
            value_list_zone.append(0)
            value_list_state.append(0)

In [209]:
df.Zone.fillna(0)

0        Cuyahoga County, OH, USA
1         Fairfax County, VA, USA
2             Washington, DC, USA
3             Washington, DC, USA
4             Washington, DC, USA
                   ...
35492     Broward County, FL, USA
35493     Broward County, FL, USA
35494     Broward County, FL, USA
35495     Broward County, FL, USA
35496    Humboldt County, CA, USA
Name: Zone, Length: 35497, dtype: object

In [223]:
df['Zone'].head(90)

0     Cuyahoga County, OH, USA
1      Fairfax County, VA, USA
2          Washington, DC, USA
3          Washington, DC, USA
4          Washington, DC, USA
                ...
85    Beaufort County, SC, USA
86    Beaufort County, SC, USA
87      Walton County, FL, USA
88     Brevard County, FL, USA
89       Duval County, FL, USA
Name: Zone, Length: 90, dtype: object

In [210]:
df.State.fillna(0)

0                        Ohio, USA
1                    Virginia, USA
2        District of Columbia, USA
3        District of Columbia, USA
4        District of Columbia, USA
                   ...
35492                 Florida, USA
35493                 Florida, USA
35494                 Florida, USA
35495                 Florida, USA
35496              California, USA
Name: State, Length: 35497, dtype: object

In [217]:
value_list_zone_1 = []
value_list_state_1 = []
index_list_df = df.index.tolist()

for i in index_list_df:
    if df['Zone'][i] == 0:
        str2 = "https://geo.fcc.gov/api/census/area?lat="+str(df["Lat"][i]).replace(" ","")+"&lon="+str(df["Long"][i]).replace(" ","")+"&format=json"
        with urllib.request.urlopen(str2) as url:
            data = json.loads(url.read().decode())
            if len(data['results']) != 0:
                value_list_zone_1.append(data['results'][0]['county_name'] + " County, " + data['results'][0]['state_code'] + ", USA")
                value_list_state_1.append(data['results'][0]['state_name'] + ", USA")

In [220]:
value_list_zone_1

[]

In [189]:
value_list_zone

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 'Colleton County, SC, USA',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 'Carteret County, NC, USA',
 0,
 0,
 'Essex County, MA, USA',
 'Durham County, NC, USA',
 'Wake County, NC, USA',
 'Marin County, CA, USA',
 'New Haven County, CT, USA',
 'Barnstable County, MA, USA',
 'Ventura County, CA, USA',
 'Barnstable County, MA, USA',
 'Walton County, FL, USA',
 'Contra Costa County, CA, USA',
 'Alameda County, CA, USA',
 'St. Johns County, FL, USA',
 'New Haven County, CT, USA',
 'Marin County, CA, USA',
 'Orleans County, LA, USA',
 'Lincoln County, OR, USA',
 'San Luis Obispo County, CA, USA',
 'Suffolk County, MA, USA',
 'King County, WA, USA',
 'Palm Beach County, FL, USA',
 'Tillamook County, OR, USA',
 'Maui County, HI, USA',
 'New Haven County, CT, USA',
 'Cameron County, LA, USA',
 'Cameron County, LA, USA',
 'Cameron County, LA, USA',
 'Cameron County, LA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Los Angeles County, CA, USA',
 'Marin County, CA, USA',
 'Norfolk County, MA, USA',
 'Plymouth County, MA, USA',
 'Plymouth County, MA, USA',
 'Plymouth County, MA, USA',
 'Barnstable County, MA, USA',
 'San Diego County, CA, USA',
 'West Baton Rouge County, LA, USA',
 'Essex County, MA, USA',
 'Barnstable County, MA, USA',
 'Galveston County, TX, USA',
 'Cape May County, NJ, USA',
 'Cape May County, NJ, USA',
 'Queens County, NY, USA',
 'Queens County, NY, USA',
 'Jefferson County, TX, USA',
 'Barnstable County, MA, USA',
 'Suffolk County, MA, USA',
 'District of Columbia County, DC, USA',
 'District of Columbia County, DC, USA',
 'Okeechobee County, FL, USA',
 'Suffolk County, NY, USA',
 'Barnstable County, MA, USA',
 'Norfolk County, MA, USA',
 'Barnstable County, MA, USA',
 'Barnstable County, MA, USA',
 'Los Angeles County, CA, USA',
 'St. Johns County, FL, USA',
 'Charlotte County, FL, USA',
 'Palm Beach County, FL, USA',
 'New Haven County, CT, USA',
 'Kenai Peninsula County, AK, USA',
 'Kenai Peninsula County, AK, USA',
 'Kenai Peninsula County, AK, USA',
 'Essex County, MA, USA',
 'Suffolk County, MA, USA',
 'Bristol County, MA, USA',
 'Palm Beach County, FL, USA',
 'Providence County, RI, USA',
 'Miami-Dade County, FL, USA',
 'Essex County, MA, USA',
 'Multnomah County, OR, USA',
 'Miami-Dade County, FL, USA',
 'Barnstable County, MA, USA',
 'Santa Barbara County, CA, USA',
 'Kenai Peninsula County, AK, USA',
 'Marion County, OR, USA',
 'Chittenden County, VT, USA',
 'Baltimore County, MD, USA',
 'Barnstable County, MA, USA',
 'New Castle County, DE, USA',
 'Whatcom County, WA, USA',
 'Sonoma County, CA, USA',
 'Sonoma County, CA, USA',
 'San Luis Obispo County, CA, USA',
 'Sonoma County, CA, USA',
 'Carteret County, NC, USA',
 'Indian River County, FL, USA',
 'Essex County, MA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Hampton City County, VA, USA',
 'Norfolk City County, VA, USA',
 'Essex County, MA, USA',
 'Ocean County, NJ, USA',
 'San Diego County, CA, USA',
 'Suffolk County, NY, USA',
 'Miami-Dade County, FL, USA',
 'Martin County, FL, USA',
 'Baldwin County, AL, USA',
 'Placer County, CA, USA',
 'Essex County, MA, USA',
 'Queens County, NY, USA',
 'Los Angeles County, CA, USA',
 'Miami-Dade County, FL, USA',
 'Leelanau County, MI, USA',
 'Allegan County, MI, USA',
 'Kenai Peninsula County, AK, USA',
 'Carteret County, NC, USA',
 'Wake County, NC, USA',
 'Wake County, NC, USA',
 'Essex County, MA, USA',
 'Willacy County, TX, USA',
 'Coos County, OR, USA',
 'Miami-Dade County, FL, USA',
 'Duval County, FL, USA',
 'Duval County, FL, USA',
 'Los Angeles County, CA, USA',
 'San Mateo County, CA, USA',
 'San Mateo County, CA, USA',
 'Palm Beach County, FL, USA',
 'Palm Beach County, FL, USA',
 'Somerset County, MD, USA',
 'Los Angeles County, CA, USA',
 'Suffolk County, NY, USA',
 'Los Angeles County, CA, USA',
 'Nueces County, TX, USA',
 'Marin County, CA, USA',
 'Glynn County, GA, USA',
 'Los Angeles County, CA, USA',
 'Monterey County, CA, USA',
 'Palm Beach County, FL, USA',
 'Nassau County, FL, USA',
 'Miami-Dade County, FL, USA',
 'Galveston County, TX, USA',
 'Los Angeles County, CA, USA',
 'Broward County, FL, USA',
 'Colleton County, SC, USA',
 'Palm Beach County, FL, USA',
 'Nueces County, TX, USA',
 'Pinellas County, FL, USA',
 'Nueces County, TX, USA',
 'Pinellas County, FL, USA',
 'Pinellas County, FL, USA',
 'Monmouth County, NJ, USA',
 'Monmouth County, NJ, USA',
 'Pinellas County, FL, USA',
 'Pinellas County, FL, USA',
 0]

In [182]:
str1 = ""
str2 = ""
zone = ""
state = ""
for i in index_list:
    str2 = "https://geo.fcc.gov/api/census/area?lat="+str(df1["Lat"][i]).replace(" ","")+"&lon="+str(df1["Long"][i]).replace(" ","")+"&format=json"
    with urllib.request.urlopen(str2) as url:
        data = json.loads(url.read().decode())
        if len(data['results']) != 0:
            print(data['results'][0]['county_name'])
            zone = data['results'][0]['county_name'] + " County, " + data['results'][0]['state_code'] + ", USA"
            state = data['results'][0]['state_name'] + ", USA"
            df1['Zone'][i] = zone
            df1['State'][i] = state
            print(zone)
            print(state)
        else:
            continue

Colleton
Colleton County, SC, USA
South Carolina, USA

C:\Users\Aishwarya\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Aishwarya\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Carteret
Carteret County, NC, USA
North Carolina, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Durham
Durham County, NC, USA
North Carolina, USA
Wake
Wake County, NC, USA
North Carolina, USA
Marin
Marin County, CA, USA
California, USA
New Haven
New Haven County, CT, USA
Connecticut, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Ventura
Ventura County, CA, USA
California, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Walton
Walton County, FL, USA
Florida, USA
Contra Costa
Contra Costa County, CA, USA
California, USA
Alameda
Alameda County, CA, USA
California, USA
St. Johns
St. Johns County, FL, USA
Florida, USA
New Haven
New Haven County, CT, USA
Connecticut, USA
Marin
Marin County, CA, USA
California, USA
Orleans
Orleans County, LA, USA
Louisiana, USA
Lincoln
Lincoln County, OR, USA
Oregon, USA
San Luis Obispo
San Luis Obispo County, CA, USA
California, USA
Suffolk
Suffolk County, MA, USA
Massachusetts, USA
King
King County, WA, USA
Washington, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Tillamook
Tillamook County, OR, USA
Oregon, USA
Maui
Maui County, HI, USA
Hawaii, USA
New Haven
New Haven County, CT, USA
Connecticut, USA
Cameron
Cameron County, LA, USA
Louisiana, USA
Cameron
Cameron County, LA, USA
Louisiana, USA
Cameron
Cameron County, LA, USA
Louisiana, USA
Cameron
Cameron County, LA, USA
Louisiana, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Marin
Marin County, CA, USA
California, USA
Norfolk
Norfolk County, MA, USA
Massachusetts, USA
Plymouth
Plymouth County, MA, USA
Massachusetts, USA
Plymouth
Plymouth County, MA, USA
Massachusetts, USA
Plymouth
Plymouth County, MA, USA
Massachusetts, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
San Diego
San Diego County, CA, USA
California, USA
West Baton Rouge
West Baton Rouge County, LA, USA
Louisiana, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Galveston
Galveston County, TX, USA
Texas, USA
Cape May
Cape May County, NJ, USA
New Jersey, USA
Cape May
Cape May County, NJ, USA
New Jersey, USA
Queens
Queens County, NY, USA
New York, USA
Queens
Queens County, NY, USA
New York, USA
Jefferson
Jefferson County, TX, USA
Texas, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Suffolk
Suffolk County, MA, USA
Massachusetts, USA
District of Columbia
District of Columbia County, DC, USA
District of Columbia, USA
District of Columbia
District of Columbia County, DC, USA
District of Columbia, USA
Okeechobee
Okeechobee County, FL, USA
Florida, USA
Suffolk
Suffolk County, NY, USA
New York, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Norfolk
Norfolk County, MA, USA
Massachusetts, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
St. Johns
St. Johns County, FL, USA
Florida, USA
Charlotte
Charlotte County, FL, USA
Florida, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
New Haven
New Haven County, CT, USA
Connecticut, USA
Kenai Peninsula
Kenai Peninsula County, AK, USA
Alaska, USA
Kenai Peninsula
Kenai Peninsula County, AK, USA
Alaska, USA
Kenai Peninsula
Kenai Peninsula County, AK, USA
Alaska, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Suffolk
Suffolk County, MA, USA
Massachusetts, USA
Bristol
Bristol County, MA, USA
Massachusetts, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Providence
Providence County, RI, USA
Rhode Island, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Multnomah
Multnomah County, OR, USA
Oregon, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
Santa Barbara
Santa Barbara County, CA, USA
California, USA
Kenai Peninsula
Kenai Peninsula County, AK, USA
Alaska, USA
Marion
Marion County, OR, USA
Oregon, USA
Chittenden
Chittenden County, VT, USA
Vermont, USA
Baltimore
Baltimore County, MD, USA
Maryland, USA
Barnstable
Barnstable County, MA, USA
Massachusetts, USA
New Castle
New Castle County, DE, USA
Delaware, USA
Whatcom
Whatcom County, WA, USA
Washington, USA
Sonoma
Sonoma County, CA, USA
California, USA
Sonoma
Sonoma County, CA, USA
California, USA
San Luis Obispo
San Luis Obispo County, CA, USA
California, USA
Sonoma
Sonoma County, CA, USA
California, USA
Carteret
Carteret County, NC, USA
North Carolina, USA
Indian River
Indian River County, FL, USA
Florida, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Hampton City
Hampton City County, VA, USA
Virginia, USA
Norfolk City
Norfolk City County, VA, USA
Virginia, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Ocean
Ocean County, NJ, USA
New Jersey, USA
San Diego
San Diego County, CA, USA
California, USA
Suffolk
Suffolk County, NY, USA
New York, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Martin
Martin County, FL, USA
Florida, USA
Baldwin
Baldwin County, AL, USA
Alabama, USA
Placer
Placer County, CA, USA
California, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Queens
Queens County, NY, USA
New York, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Leelanau
Leelanau County, MI, USA
Michigan, USA
Allegan
Allegan County, MI, USA
Michigan, USA
Kenai Peninsula
Kenai Peninsula County, AK, USA
Alaska, USA
Carteret
Carteret County, NC, USA
North Carolina, USA
Wake
Wake County, NC, USA
North Carolina, USA
Wake
Wake County, NC, USA
North Carolina, USA
Essex
Essex County, MA, USA
Massachusetts, USA
Willacy
Willacy County, TX, USA
Texas, USA

Coos
Coos County, OR, USA
Oregon, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Duval
Duval County, FL, USA
Florida, USA
Duval
Duval County, FL, USA
Florida, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
San Mateo
San Mateo County, CA, USA
California, USA
San Mateo
San Mateo County, CA, USA
California, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Somerset
Somerset County, MD, USA
Maryland, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Suffolk
Suffolk County, NY, USA
New York, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Nueces
Nueces County, TX, USA
Texas, USA
Marin
Marin County, CA, USA
California, USA
Glynn
Glynn County, GA, USA
Georgia, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Monterey
Monterey County, CA, USA
California, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Nassau
Nassau County, FL, USA
Florida, USA
Miami-Dade
Miami-Dade County, FL, USA
Florida, USA
Galveston
Galveston County, TX, USA
Texas, USA
Los Angeles
Los Angeles County, CA, USA
California, USA
Broward
Broward County, FL, USA
Florida, USA
Colleton
Colleton County, SC, USA
South Carolina, USA
Palm Beach
Palm Beach County, FL, USA
Florida, USA
Nueces
Nueces County, TX, USA
Texas, USA
Pinellas
Pinellas County, FL, USA
Florida, USA
Nueces
Nueces County, TX, USA
Texas, USA
Pinellas
Pinellas County, FL, USA
Florida, USA
Pinellas
Pinellas County, FL, USA
Florida, USA
Monmouth
Monmouth County, NJ, USA
New Jersey, USA
Monmouth
Monmouth County, NJ, USA
New Jersey, USA
Pinellas
Pinellas County, FL, USA
Florida, USA
Pinellas
Pinellas County, FL, USA
Florida, USA

In [190]:
df1['Zone'] = value_list_zone

C:\Users\Aishwarya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [191]:
df1['State'] = value_list_state

C:\Users\Aishwarya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [194]:
df1.tail(50)

,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
24605,"Baldwin County, AL, USA","Alabama, USA",United States,"Watercraft (powerboat, sailboat, kayak or canoe)",9/15/18,Ono Island,25,5,30,317,...,0,0,0,0,32,3,61,1159,30.297552372286,-87.498954120463
24678,"Placer County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",1/9/19,NaN,1,0,1,8,...,0,0,0,1,0,0,37,129,38.75654,-121.1389
24680,"Essex County, MA, USA","Massachusetts, USA",United States,"Land (beach, shoreline and inland)",11/29/18,MA-CZM,20,0,20,8,...,0,0,0,0,29,80,88,421,42.514195020354,-70.888102561945
24689,"Queens County, NY, USA","New York, USA",United States,Underwater,9/16/18,Beach 8th Street - Project Aware,1,0,1,92,...,0,0,0,0,0,0,3,114,40.59457323,-73.74252176
24700,"Los Angeles County, CA, USA","California, USA",United States,Underwater,10/17/18,Veterans Park - Project Aware,2,0,2,4,...,0,0,0,0,0,0,0,5,33.83633383,-118.3922557
24727,"Miami-Dade County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",1/13/19,Us sailing,2,0,2,17,...,0,0,0,0,0,0,220,473,25.73018,-80.23321
25341,"Leelanau County, MI, USA","Michigan, USA",United States,"Land (beach, shoreline and inland)",9/15/18,Elm Pointe Park - A4GL,20,0,20,5,...,3,0,1,0,7,1,43,250,45.17912,-86.16112
25493,"Allegan County, MI, USA","Michigan, USA",United States,"Land (beach, shoreline and inland)",10/31/18,Saugatuck Dunes State Park Shoreline Beach - A4GL,27,0,27,25,...,1,0,0,0,45,4,80,436,42.69586,-86.20847
25506,"Kenai Peninsula County, AK, USA","Alaska, USA",United States,"Land (beach, shoreline and inland)",9/22/18,CACS Coast Walk,2,0,2,2,...,0,0,0,0,5,0,0,35,59.716006247475,-151.02801520592
25575,"Carteret County, NC, USA","North Carolina, USA",United States,"Land (beach, shoreline and inland)",9/15/18,NCDOT- Carteret County Roads 2018 ICC,100,0,100,94215,...,0,0,0,0,0,0,1,1,34.709752925908,-76.673106522108
25603,"Wake County, NC, USA","North Carolina, USA",United States,"Land (beach, shoreline and inland)",9/15/18,Wake Co. Big Sweep - Falls Lake @ Hwy 50 boat ...,3,0,3,30,...,0,0,0,0,0,0,1,1,36.017810904686,-78.691866875757
25605,"Wake County, NC, USA","North Carolina, USA",United States,"Land (beach, shoreline and inland)",9/15/18,Wake Co. Big Sweep - Harris Lake County Park,116,0,116,2465,...,1,3,3,0,409,106,206,3940,35.620346340027,-78.925118341715
25802,"Essex County, MA, USA","Massachusetts, USA",United States,"Land (beach, shoreline and inland)",9/16/18,MA-CZM-Maney,12,0,12,38,...,0,0,0,0,12,17,82,406,42.610080727044,-70.66141072844
25946,"Willacy County, TX, USA","Texas, USA",United States,"Land (beach, shoreline and inland)",2/12/19,NaN,1,0,1,10,...,0,0,0,0,0,0,0,130,26.53061,-97.26309
26148,"Coos County, OR, USA","Oregon, USA",United States,"Land (beach, shoreline and inland)",3/26/17,Whiskey Run - The Grieves,2,2,4,200,...,0,0,2,0,0,0,0,159,43.211087080554,-124.39539943506
26165,"Miami-Dade County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",9/15/18,Vizcaya Museum and Gardens,7,6,13,96,...,0,1,1,0,30,3,212,1198,25.744128896104,-80.209888190732
26895,"Duval County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/6/19,Fls jovens,2,0,2,0,...,0,0,0,0,0,0,0,3,30.3224,-81.39432
26901,"Duval County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/6/19,NaN,1,0,1,1,...,0,0,0,1,0,0,3,29,30.32175,-81.3942
26925,"Los Angeles County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/7/19,1,4,0,4,3,...,0,0,0,0,0,0,8,157,33.75767,-118.13034
26995,"San Mateo County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/10/19,92 bay,1,0,1,0,...,0,0,0,0,0,0,0,2,37.57377,-122.26329
26996,"San Mateo County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/10/19,92 bay,1,0,1,0,...,0,0,0,0,0,0,0,1,37.57378,-122.26333
27012,"Palm Beach County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/11/19,NaN,1,0,1,0,...,0,0,0,0,0,0,0,0,26.47891,-80.05456
27013,"Palm Beach County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/11/19,NaN,1,0,1,0,...,0,0,0,1,0,0,4,17,26.48912,-80.05326
27016,"Somerset County, MD, USA","Maryland, USA",United States,"Land (beach, shoreline and inland)",4/11/19,Janes Island cleanup,4,0,4,12,...,0,0,0,0,0,0,32,140,38.01572,-75.87199
27030,"Los Angeles County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/11/19,NaN,1,0,1,8,...,0,0,0,6,0,0,79,196,34.0123,-118.50193
27107,"Suffolk County, NY, USA","New York, USA",United States,"Land (beach, shoreline and inland)",4/13/19,EI Beach Cleanup 2019,1,0,1,7,...,0,0,0,3,0,0,39,96,40.69829,-73.15514
27321,"Los Angeles County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/21/19,Independent,3,0,3,6,...,0,0,0,7,0,0,20,165,34.00893,-118.49809
27344,"Nueces County, TX, USA","Texas, USA",United States,"Land (beach, shoreline and inland)",4/22/19,Adopt a beach,2,0,2,0,...,0,0,0,0,0,0,5,24,27.80649,-97.07254
27349,"Marin County, CA, USA","California, USA",United States,"Watercraft (powerboat, sailboat, kayak or canoe)",4/22/19,NaN,1,0,1,2,...,0,0,0,0,0,0,0,30,37.9161,-122.47547
27402,"Glynn County, GA, USA","Georgia, USA",United States,"Land (beach, shoreline and inland)",4/23/19,NaN,1,0,1,0,...,0,0,0,0,0,0,0,1,31.04677,-81.41021
27433,"Los Angeles County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/24/19,Alvin and Alanna,2,0,2,2,...,0,0,0,1,0,0,4,41,33.98939,-118.47876
27475,"Monterey County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/25/19,Cisco,5,0,5,8,...,0,0,0,4,0,0,91,145,36.60223,-121.8769
27602,"Palm Beach County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/27/19,Ocean Conservancy and Pura Vida Divers,1,0,1,22,...,0,0,0,1,0,0,185,448,26.78079,-80.04035
27610,"Nassau County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/27/19,Greco's,13,0,13,2,...,0,0,0,0,0,0,26,75,30.66971,-81.43025
27613,"Miami-Dade County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/27/19,Super sabers,4,0,4,16,...,0,0,0,2,0,0,29,332,25.7262,-80.23877
27617,"Galveston County, TX, USA","Texas, USA",United States,"Land (beach, shoreline and inland)",4/27/19,Team Fairyedragon,3,0,3,4,...,0,0,0,1,0,0,29,103,29.26371,-94.83088
27721,"Los Angeles County, CA, USA","California, USA",United States,"Land (beach, shoreline and inland)",4/27/19,NaN,2,0,2,2,...,0,0,0,0,0,0,62,102,34.01295,-118.50243
27794,"Broward County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",4/28/19,NaN,1,0,1,11,...,0,0,0,1,0,0,65,140,26.21648,-80.09028
27884,"Colleton County, SC, USA","South Carolina, USA",United States,"Land (beach, shoreline and inland)",4/30/19,EBSP Turtle Patrol,1,0,1,2,...,0,0,0,1,0,0,3,65,32.50469,-80.29404
27908,"Palm Beach County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/1/19,NaN,1,0,1,3,...,0,0,0,5,0,0,25,103,26.46823,-80.05698
27919,"Nueces County, TX, USA","Texas, USA",United States,"Land (beach, shoreline and inland)",5/1/19,Adopt a beach,1,0,1,0,...,0,0,0,0,0,0,0,3,27.8005,-97.07769
27941,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/2/19,Sea turtle trackers,1,0,1,0,...,0,0,0,0,0,0,0,3,27.68928,-82.73841
27944,"Nueces County, TX, USA","Texas, USA",United States,"Land (beach, shoreline and inland)",5/2/19,Adopt a beach,2,0,2,1,...,0,0,0,0,0,0,0,5,27.80689,-97.07242
27959,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/3/19,Sea turtle trackers,1,0,1,2,...,0,0,0,0,0,0,1,16,27.71109,-82.73924
27974,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/3/19,Sea Turtle Trackers,2,0,2,2,...,0,0,0,2,0,0,2,41,27.73401,-82.75023
27985,"Monmouth County, NJ, USA","New Jersey, USA",United States,"Land (beach, shoreline and inland)",5/4/19,Gigi2,1,0,1,2,...,0,0,0,0,0,0,27,71,40.34833,-73.97259
27997,"Monmouth County, NJ, USA","New Jersey, USA",United States,"Land (beach, shoreline and inland)",5/4/19,Gigi2,1,0,1,5,...,0,0,0,0,0,0,3,130,40.34444,-73.97296
28032,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/5/19,NaN,2,0,2,0,...,0,0,0,0,0,0,0,6,27.69774,-82.73294
28036,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/5/19,NaN,2,0,2,0,...,0,0,0,0,0,0,3,17,27.69634,-82.73813
34410,0,0,United States,"Land (beach, shoreline and inland)",9/21/19,Citrus County Aquatic Services,440,75,515,4120,...,8,5,21,0,438,355,617,7924,28.635674604683,-83.133995150659

In [173]:
df1.tail(2)

,Zone,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
28036,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",5/5/19,NaN,2,0,2,0,...,0,0,0,0,0,0,3,17,27.69634,-82.73813
34410,"Pinellas County, FL, USA","Florida, USA",United States,"Land (beach, shoreline and inland)",9/21/19,Citrus County Aquatic Services,440,75,515,4120,...,8,5,21,0,438,355,617,7924,28.635674604683,-83.133995150659

In [204]:
index_list_df = df.index.tolist()
full_list_of_zones = []
count = 0
for i in index_list_df:
    
    if i not in index_list:
        full_list_of_zones.append(df['Zone'][i])
    elif i in index_list:
        full_list_of_zones.append(value_list_zone[count])
        count = count + 1

In [207]:
full_list_of_zones[34410]

0

In [113]:
first_column = df1.columns[0]
df = df.drop([first_column], axis=1)

In [114]:
df.head(2)

,Unnamed: 0,State,Country,Cleanup Type,Cleanup Date,Group Name,Adults,Children,People,Pounds,...,Diapers,Syringes,Tampons/Tampon Applicators,Personal Hygiene (Clean Swell),Foam Pieces,Glass Pieces,Plastic Pieces,Total Items Collected,Lat,Long
0,1,"Ohio, USA",United States,"Land (beach, shoreline and inland)",12/22/14,NaN,1,0,1,0,...,0,0,0,0,0,0,0,3,41.49742,-81.56505
1,2,"Virginia, USA",United States,"Land (beach, shoreline and inland)",12/24/14,NaN,1,0,1,0,...,0,0,0,0,0,0,2,10,38.87456,-77.24428